### PR TITLE
updated screener

### PR DESCRIPTION
**Pull request by iforgotmypass**

### CODE REVIEW

**Comment by daxm** [comment]
Did I miss them when I initially build this method or were these options just added?  My apologies if I just missed them.

Thanks for the PR!

**Comment by iforgotmypass** [comment]
Actually I don't know, I'm using this API since yesterday and I've just found your python module, it's great! Is this PR already available in the PyPi package?

**Comment by daxm** [comment]
It is now.  :-)  20210217.0

**Comment by iforgotmypass** [comment]
Thank you!

**Comment by daxm** [comment]
I don't know how else to communicate with you so I'm putting it on this PR.

I'm a bit over-busy right now.  Would you be willing to add in the "insider_trading" method?  I swear I had added everything in back in December but either FMP made changes or I missed this.

**Comment by iforgotmypass** [comment]
Sure! I'll work on it tomorrow!

**Pull request merged**
