### PR TITLE
add support for institutional symbol ownership API

### PR DESCRIPTION
**Pull request by ivelin**
Docs:
https://site.financialmodelingprep.com/developer/docs/institutional-stock-ownership-api/?direct=true

### CODE REVIEW

**Comment by daxm** [comment]
Code looks good!  Can you run black against it so that it'll pass the commit checks?

**Comment by ivelin** [comment]
> Code looks good! Can you run black against it so that it'll pass the commit checks?

I did actuall run black this time before the PR. From the error messages, it appears that two other files that I have not changed are now breaking black:

```
Run black fmpsdk --check --exclude "venv|build"
would reformat /home/runner/work/fmpsdk/fmpsdk/fmpsdk/senate.py
would reformat /home/runner/work/fmpsdk/fmpsdk/fmpsdk/shares_float.py

Oh no! 💥 💔 💥
2 files would be reformatted, 20 files would be left unchanged.
Error: Process completed with exit code 1.
```

**Comment by daxm** [comment]
Do you have up-to-date black package?  It looks like the checker does a fresh install of black each time so I'm guessing it is running the most current.

I updated black locally and ran it.  I see no changes to the files.

**Comment by ivelin** [comment]
Yes, I am running latest version of black.
The strange thing is that my PR is only suggesting 1 file change (see Files Changed tab).
So it appears that the latest version of black used by the github action is complaining about two files that have been committed prior to this PR.

**Comment by daxm** [comment]
ok.  Let me see if I can merge regardless and deal with black issues later.It is far better to grasp the Universe as it really is than to persist in delusion, however satisfying and reassuring.  — Carl SaganOn Jan 30, 2024, at 14:02, Ivelin Ivanov ***@***.***> wrote:﻿
Yes, I am running latest version of black.
The strange thing is that my PR is only suggesting 1 file change (see Files Changed tab).
So it appears that the latest version of black used by the github action is complaining about two files that have been committed prior to this PR.

**Pull request merged**
