### PR TITLE
Add function for the analyst_estimates API

### PR DESCRIPTION
**Pull request by ivelin**
https://site.financialmodelingprep.com/developer/docs#analyst-estimates-company-information

### CODE REVIEW

**Comment by ivelin** [comment]
Tested this implementation in my current project:
https://github.com/ivelin/canswim/blob/main/prepare_data.ipynb

**Review by daxm — COMMENTED** [review]
Why is "    Note: Between the "from" and "to" parameters the maximum time interval can be 3 months." in the docstring?

**Comment by daxm** [comment]
black test failed.  Please run black against your code to fix formatting.

**Comment by ivelin** [comment]
> Why is " Note: Between the "from" and "to" parameters the maximum time interval can be 3 months." in the docstring?

Sorry. Copy/paste overlook. Deleted.

**Comment by daxm** [comment]
I'll make a new build and publish to pypi soon.

**Comment by ivelin** [comment]
Great! Thank you for leading an awesome project!

**Pull request merged**
